### PR TITLE
update data values file and increment the chart and parent charts acc…

### PR DESCRIPTION
**Pull request by moosecanswim**
…ordingly

**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.

<br/><br/>

2. What **changes to custom.yaml** are required?

<br/><br/>

3. Have you documented any additional setup steps or configurations options?

<br/><br/>

4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

<br/><br/>

### CODE REVIEW

**Review by chrisbsmith — COMMENTED** [review]
@moosecanswim why are we just incrementing the chart files when there's no change to the charts themselves?

**Comment by moosecanswim** [comment]
I incremented the data version which means we should increment the chart.yaml version so the change gets published.  data is wrapped in gm-data parent chart so that has to get updated too.  Tho it does not really matter cause this chart will be pulled out of this repo soon

**Comment by chrisbsmith** [comment]
> I incremented the data version which means we should increment the chart.yaml version so the change gets published. data is wrapped in gm-data parent chart so that has to get updated too. Tho it does not really matter cause this chart will be pulled out of this repo soon

I get the versioning aspect, but was more curious why we were incrementing the version with no code changes.

**Comment by moosecanswim** [comment]
> I get the versioning aspect, but was more curious why we were incrementing the version with no code changes.

I dont think we should treat the values files different from the code.  In an ideal world the people deploying these services would understand a difference but from my experience they dont get that.

if we increment the chart version then we get the ability to say 

hey paul if you want data 1.1.4 run `helm install data decipher/data --version 3.0.5` if you want data 1.1.2 use `--version 3.0.5`

seems easier than saying hey paul install this version then change the value data.image.

**Comment by chrisbsmith** [comment]
> > I get the versioning aspect, but was more curious why we were incrementing the version with no code changes.
> 
> I dont think we should treat the values files different from the code. In an ideal world the people deploying these services would understand a difference but from my experience they dont get that.
> 
> if we increment the chart version then we get the ability to say
> 
> hey paul if you want data 1.1.4 run `helm install data decipher/data --version 3.0.5` if you want data 1.1.2 use `--version 3.0.5`
> 
> seems easier than saying hey paul install this version then change the value data.image.

I agree.  This change then is only to increment the `appVersion` then?  I suppose there was another PR that updated the values files for the `1.1.5` docker images

**Comment by chrisbsmith** [comment]
@moosecanswim can you please look into this again.

**Comment by moosecanswim** [comment]
@chrisbsmith I think we can drop this pr since we're not deploying data with the mesh.  We should probably drop data entirely from the repo

**Comment by chrisbsmith** [comment]
@moosecanswim we didn't get this merged in before the update to `main`. Do we still need it?

**Comment by moosecanswim** [comment]
@chrisbsmith correct we did not merge this in

**Comment by chrisbsmith** [comment]
But do we need it?

**Comment by moosecanswim** [comment]
If we are pulling data out of the core helm charts then we dont need it.

**Comment by chrisbsmith** [comment]
Closing this PR as we'll be removing GM Data from the core GM Helm Charts.

**Pull request closed without merging**
