### PR TITLE
Add sidecar proxy onto control

### LINKED ISSUE #749: gm-control should be behind a sidecar
now that HTTP2 support is full in the mesh (no downgrade) we can put gm-control behind a managed sidecar so that it registers in the dashboard, collects metrics, and can be accessed outside via edge

### PR DESCRIPTION
**Pull request by jack-bischoff**
**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.

This PR follows from https://github.com/greymatter-io/helm-charts/pull/785, but is updated with release-2.4 commits and is set to merge back into into release-2.4 instead of release-2.3.
Closes #749 
<br/><br/>

2. What **changes to custom.yaml** are required?
None.
<br/><br/>

3. Have you documented any additional setup steps or configurations options?
None.
<br/><br/>

4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

- Spin up a kubernetes cluster with AWS (connect to the vpn): http://docs.greymatter.services/runbooks/kops-cluster/
- Checkout out this branch: `git checkout 749-sidecar-on-control
- Generate credentials (if they do not exist): `make credentials`
- Apply secrets: `make secrets`
- In `edge/values.yaml` change `ingress.type` to `LoadBalancer`
- Install Grey Matter: `make install`
- Run: `kubectl patch svc edge -p '{"metadata":{"annotations":{"service.beta.kubernetes.io/aws-load-balancer-internal":"true"}}}'`
- Run: `kubectl get svc` -- Copy the external IP on the edge service.
- Navigate to `https://{external-ip}:10808`

It may take a while for the url to resolve.
<br/><br/>

### CODE REVIEW

**Comment by jack-bischoff** [comment]
@kaitmore It sounded like a gm-catalog image > 1.2.0 would solve this issue, but the dashboard is still showing all the services as down with catalog 1.2.2.

I'm also getting an "Error communication with Prometheus" message when clicking on a service. I double backed and checked if this issue was occurring in the old branch and it does, so I don't think it was caused by any merging I performed.

**Comment by kaitmore** [comment]
@jack-bischoff Hmm, I just installed this branch on k3d and everything works fine for me. All services are green, no prometheus errors.

**Comment by jack-bischoff** [comment]
Control is still logging nonce errors for every service @alecholmez

**Comment by jack-bischoff** [comment]
After initial setup logs, Catalog throws these errors:
```{"level":"info","service":"gm-catalog","package":"xdsretriever","zoneName":"zone-default-zone","time":"2021-01-27T21:55:22.141256303Z","message":"Retrieving cluster instances"}
{"level":"warn","service":"gm-catalog","package":"xdsretriever","zoneName":"zone-default-zone","discovery.NewXDSSession":"write tcp 100.96.3.193:60406->100.64.234.32:10808: write: broken pipe","time":"2021-01-27T21:55:23.164543276Z","message":"Unable to create xDS client connection, retrying in 10s"}```

**Comment by tilleryd** [comment]
@jack-bischoff I am seeing the same thing you are with k3d.

**Comment by jack-bischoff** [comment]
Sidecars on prometheus and jwt periodically throw this error:
`[2021-01-28 17:39:05.840][6][warning][config] [bazel-out/k8-fastbuild/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:93] StreamAggregatedResources gRPC config stream closed: 2, stream timeout`

**Comment by tilleryd** [comment]
@jack-bischoff You will need to configure catalog to connect to the control sidecar via TLS. See this PR for how to do that https://github.com/greymatter-io/gm-catalog/pull/385.

**Comment by jack-bischoff** [comment]
Catalog was experiencing tls errors while directly connecting to control's sidecar. Routing its connection through its own sidecar may have solved this issue, but an `unknown port` error is now appearing:
```
{"level":"warn","service":"gm-catalog","package":"xdsretriever","zoneName":"zone-default-zone","discovery.NewXDSSession":"connection error: desc = \"transport: error while dialing: dial tcp: address tcp/10909/control/: unknown port\"","time":"2021-01-30T00:06:48.150833035Z","message":"Unable to create xDS client connection, retrying in 10s"}
```
Requests on the egress url `localhost:10909/control/` from within the catalog container properly appear in the control sidecar logs (503 is expected for a http request), so routing should be fine. This might be a problem between control and control's sidecar. 

New mesh objects with egress can be found in the temp folder `catalog-egress-mesh-objects/`. Once a working set has been found, they should be migrated to the control-api json folder and properly templated. Before applying them, make sure to delete the pre-loaded catalog mesh objects. 

Configure Catalog's control endpoint with the environment variables:
``` 
        - name: CONTROL_SERVER_0_ZONE_NAME
          value: "zone-default-zone"
        - name: CONTROL_SERVER_0_REQUEST_CLUSTER
          value: "edge"
        - name: CONTROL_SERVER_0_ADDRESS
          value: "localhost:10909/control/"
        - name: CONTROL_SERVER_0_USE_TLS
          value: "false"
        - name: CONTROL_SERVER_0_CERT_PATH
          value: ""
        - name: CONTROL_SERVER_0_KEY_PATH
          value: ""
        - name: CONTROL_SERVER_0_CA_PATH
          value: ""
```
Or by PUTing /zone with its zone object:
```
{
  "zoneName": "zone-default-zone",
  "requestCluster": "edge",
  "serverAddress": "localhost:10909/control/",
  "useTls": false
}
```

**Comment by kaitmore** [comment]
This is a really strange issue, and catalog is only a symptom. Sidecars somehow _initially_ receive their configurations from control through it’s proxy, but then the connection is closed. For example, Edge has all the right clusters, but when you look at it's xds_cluster, there are a ton of error rq/cx and none are successful:

```sh
$ curl localhost:8001/clusters
xds_cluster::10.43.177.208:10808::cx_active::8
xds_cluster::10.43.177.208:10808::cx_connect_fail::457
xds_cluster::10.43.177.208:10808::cx_total::489
xds_cluster::10.43.177.208:10808::rq_active::0
xds_cluster::10.43.177.208:10808::rq_error::7428
xds_cluster::10.43.177.208:10808::rq_success::0
xds_cluster::10.43.177.208:10808::rq_timeout::0
xds_cluster::10.43.177.208:10808::rq_total::6862
```

And all sidecar logs, including control's, have:

```
[2021-02-05 14:15:12.242][8][warning][config] [bazel-out/k8-fastbuild/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:93] StreamEndpoints gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure
```

I’m able to curl the control server directly and receive binary data. I know this is a grpc server so curl is not the best tool, but I assumed the binary data is the grpc data that isn't being decoded (this could very well be a bad assumption):

```
/app $ curl -k --cacert /etc/proxy/tls/sidecar/ca.crt --cert /etc/proxy/tls/sidecar/server.crt --key /etc/proxy/tls/sidecar/server.key https://localhost:50000
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
```

But curling through the proxy I see: 
```
/app $ curl -k --cacert /etc/proxy/tls/sidecar/ca.crt --cert /etc/proxy/tls/sidecar/server.crt --key /etc/proxy/tls/sidecar/server.key https://localhost:10808
upstream connect error or disconnect/reset before headers. reset reason: remote reset/app
```

I turned on debug logging on control's sidecar, and I can see that the connection is closed by control:

```
Authentication Successful -> USER_DN:  | EXTERNAL_SYS_DN:  | SSL_CLIENT_S_DN: C=US,ST=Virginia,L=Alexandria,O=Decipher Technology Studios,OU=Engineering,CN=greymatter
Returning headers: USER_DN: C=US,ST=Virginia,L=Alexandria,O=Decipher Technology Studios,OU=Engineering,CN=greymatter | EXTERNAL_SYS_DN: (UNSET) | SSL_CLIENT_S_DN: C=US,ST=Virginia,L=Alexandria,O=Decipher Technology Studios,OU=Engineering,CN=greymatter
[2021-02-05 14:41:54.823][45][debug][router] [external/envoy/source/common/router/router.cc:426] [C32][S9211321640271815162] cluster 'control-service' match for URL '/'
[2021-02-05 14:41:54.823][45][debug][router] [external/envoy/source/common/router/router.cc:583] [C32][S9211321640271815162] router decoding headers:
':authority', 'localhost:10808'
':path', '/'
':method', 'GET'
':scheme', 'https'
'user-agent', 'curl/7.61.1'
'accept', '*/*'
'x-forwarded-proto', 'https'
'x-request-id', '3ae12abd-b0d9-4d80-beb9-cf99b73d1f4b'
'user_dn', 'C=US,ST=Virginia,L=Alexandria,O=Decipher Technology Studios,OU=Engineering,CN=greymatter'
'ssl_client_s_dn', 'C=US,ST=Virginia,L=Alexandria,O=Decipher Technology Studios,OU=Engineering,CN=greymatter'
'x-envoy-expected-rq-timeout-ms', '60000'
'x-gm-route', 'route-control'
'x-gm-rule', 'DEFAULT'
'x-gm-shared-rules', 'control'
'x-gm-domain', '*:10808'

[2021-02-05 14:41:54.824][45][debug][pool] [external/envoy/source/common/http/conn_pool_base.cc:71] queueing request due to no available connections
[2021-02-05 14:41:54.824][45][debug][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:53] creating a new connection
[2021-02-05 14:41:54.824][45][debug][client] [external/envoy/source/common/http/codec_client.cc:35] [C33] connecting
[2021-02-05 14:41:54.824][45][debug][connection] [external/envoy/source/common/network/connection_impl.cc:753] [C33] connecting to 127.0.0.1:50000
[2021-02-05 14:41:54.824][45][debug][connection] [external/envoy/source/common/network/connection_impl.cc:769] [C33] connection in progress
[2021-02-05 14:41:54.824][45][debug][http2] [external/envoy/source/common/http/http2/codec_impl.cc:1063] [C33] updating connection-level initial window size to 268435456
[2021-02-05 14:41:54.824][45][debug][connection] [external/envoy/source/common/network/connection_impl.cc:616] [C33] connected
[2021-02-05 14:41:54.824][45][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:190] [C33] handshake expecting read
[2021-02-05 14:41:54.824][45][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:175] [C33] handshake complete
[2021-02-05 14:41:54.824][45][debug][client] [external/envoy/source/common/http/codec_client.cc:73] [C33] connected
[2021-02-05 14:41:54.825][45][debug][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:146] [C33] attaching to next request
[2021-02-05 14:41:54.825][45][debug][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:73] [C33] creating stream
[2021-02-05 14:41:54.825][45][debug][router] [external/envoy/source/common/router/upstream_request.cc:342] [C32][S9211321640271815162] pool ready
[2021-02-05 14:41:54.825][45][debug][http2] [external/envoy/source/common/http/http2/codec_impl.cc:862] [C33] stream closed: 1
[2021-02-05 14:41:54.825][45][debug][client] [external/envoy/source/common/http/codec_client.cc:115] [C33] request reset
[2021-02-05 14:41:54.825][45][debug][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:98] [C33] destroying stream: 0 remaining
[2021-02-05 14:41:54.825][45][debug][router] [external/envoy/source/common/router/router.cc:1022] [C32][S9211321640271815162] upstream reset: reset reason remote reset
[2021-02-05 14:41:54.849][45][debug][router] [external/envoy/source/common/router/router.cc:1508] [C32][S9211321640271815162] performing retry
[2021-02-05 14:41:54.850][45][debug][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:121] [C33] using existing connection
[2021-02-05 14:41:54.850][45][debug][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:73] [C33] creating stream
[2021-02-05 14:41:54.850][45][debug][router] [external/envoy/source/common/router/upstream_request.cc:342] [C32][S9211321640271815162] pool ready
[2021-02-05 14:41:54.850][45][debug][http2] [external/envoy/source/common/http/http2/codec_impl.cc:862] [C33] stream closed: 1
[2021-02-05 14:41:54.850][45][debug][client] [external/envoy/source/common/http/codec_client.cc:115] [C33] request reset
[2021-02-05 14:41:54.850][45][debug][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:98] [C33] destroying stream: 0 remaining
[2021-02-05 14:41:54.850][45][debug][router] [external/envoy/source/common/router/router.cc:1022] [C32][S9211321640271815162] upstream reset: reset reason remote reset
[2021-02-05 14:41:54.861][45][debug][router] [external/envoy/source/common/router/router.cc:1508] [C32][S9211321640271815162] performing retry
[2021-02-05 14:41:54.861][45][debug][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:121] [C33] using existing connection
[2021-02-05 14:41:54.861][45][debug][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:73] [C33] creating stream
[2021-02-05 14:41:54.861][45][debug][router] [external/envoy/source/common/router/upstream_request.cc:342] [C32][S9211321640271815162] pool ready
[2021-02-05 14:41:54.861][45][debug][http2] [external/envoy/source/common/http/http2/codec_impl.cc:862] [C33] stream closed: 1
[2021-02-05 14:41:54.861][45][debug][client] [external/envoy/source/common/http/codec_client.cc:115] [C33] request reset
[2021-02-05 14:41:54.861][45][debug][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:98] [C33] destroying stream: 0 remaining
[2021-02-05 14:41:54.862][45][debug][router] [external/envoy/source/common/router/router.cc:1022] [C32][S9211321640271815162] upstream reset: reset reason remote reset
[2021-02-05 14:41:54.862][45][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1520] [C32][S9211321640271815162] Sending local reply with details upstream_reset_before_response_started{remote reset}
[2021-02-05 14:41:54.862][45][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1777] [C32][S9211321640271815162] encoding headers via codec (end_stream=false):
':status', '503'
'content-length', '85'
'content-type', 'text/plain'
'date', 'Fri, 05 Feb 2021 14:41:54 GMT'
'server', 'envoy'
```

We need a better tool than curl to confirm success/failure, I think it would be worth using something like https://github.com/fullstorydev/grpcurl to debug this.

**Comment by chrisbsmith** [comment]
@kaitmore @jack-bischoff - following up on this PR.  Is this still in development / testing?

**Comment by chrisbsmith** [comment]
@alecholmez @jack-bischoff @kaitmore are we still working on this PR ? It's been open for a long time without any updates lately. I recommend closing it unless it's needed.

**Comment by chrisbsmith** [comment]
Closing this PR to inactivity. If we need to capture this in the future, the changes can be applied later.

**Pull request closed without merging**
