### PR TITLE
use relative paths for apiEndpoints

### PR DESCRIPTION
**Pull request by justincely**
**Please provide enough information so that others can review your pull request:**

1. the apiEndpoints for each service card has "localhost" with the default charts.  this breaks the clickthrough functionality when deploying remotely.  This can just be changed to relative paths so it works in all cases.  

<br/><br/>

2. No changes needed

<br/><br/>

3. Have you documented any additional setup steps or configurations options?

no

<br/><br/>

4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

PROOOF

<br/><br/>

### CODE REVIEW

**Comment by chrisbsmith** [comment]
@justincely please review the failed pr checks

**Comment by justincely** [comment]
@chrisbsmith done

**Comment by chrisbsmith** [comment]
@justincely somethings is wrong here. The GitHub Actions that should be firing on a PR aren't.  I need to review this before we merge.

**Comment by chrisbsmith** [comment]
Of course. I'd like to wait some time to see if they can resolve the GH Actions issue.


image

**Comment by justincely** [comment]
@chrisbsmith bumping this one back up now that the github actions stuff is fixed

**Comment by chrisbsmith** [comment]
@justincely you need to bump the fabric and sense chart versions too.  The linter doesn't catch this for some reason.

**Review by chrisbsmith — APPROVED** [review]
LGTM

**Comment by justincely** [comment]
thx

**Pull request merged**
