### PR TITLE
Link cm rs

### PR DESCRIPTION
**Pull request by moosecanswim**
**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.

This PR will automatically bounce pods when their coresponding configmaps are updated

2. What **changes to custom.yaml** are required?

none

3. Have you documented any additional setup steps or configurations options?

no additional steps

4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

To test this install the mesh like normal.  Then add a namespace to `global.control.additional_namespaces` then run a make upgrade sense.  You will notice that the porometheus pod is bounced and this is due to the configmap changed.

### CODE REVIEW

**Comment by chrisbsmith** [comment]
@moosecanswim this looks good and i'm excited to test it.  Can you look into why the test failed though?

Also, does this mean that you could change the mesh configs in the default configMaps and then the control-api-init job would kick off again?

**Comment by moosecanswim** [comment]
Well yes and no.  When you run an upgrade against fabric with the make
files it adds the flag `--no-hooks` which disables the job to run.
Therefore it will not override whats in there.  However if you were to run
a helm upgrade without that flag the job would run.

-Kyle G.

**Comment by chrisbsmith** [comment]
@moosecanswim when you get time, can you take a peek to see why the tests are failing on this PR?  I'd like to get it merged in.

**Review by chrisbsmith — APPROVED** [review]
Worked perfectly!  Nice work @moosecanswim 

LGTM

**Comment by chrisbsmith** [comment]
closed https://github.com/greymatter-io/helm-charts/issues/938

**Pull request merged**
