### PR TITLE
bump fabric chart version to 3.0.6

### PR DESCRIPTION
**Pull request by dgoldstein1**

### CODE REVIEW

**Review by chrisbsmith — APPROVED** [review]
LGTM

**Comment by chrisbsmith** [comment]
@dgoldstein1 can you submit a PR to the docs site that updates the versions listed in the install commands for GM?

**Comment by tilleryd** [comment]
I'm confused by this PR since there are no changes to the charts from 3.0.6. Why are we bumping?

**Comment by chrisbsmith** [comment]
Because we forgot to bump the fabric chart in PR #851 and the [release job failed](https://github.com/greymatter-io/helm-charts/runs/1744918079?check_suite_focus=true).  @moosecanswim is working on resolving this to ensure the linting catches it.

**Comment by tilleryd** [comment]
I'm not following. Why are we bumping a chart version for an unmerged PR? The previous PR bumped to 3.0.5 which is the latest chart thus bumping to 3.0.6 is moot.

**Comment by chrisbsmith** [comment]
let's chat.

**Pull request merged**
