### PR TITLE
WIP: 749 add sidecar to gm control

### PR DESCRIPTION
**Pull request by rahug20**
**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.

Adding a sidecar in front of gm-control.

2. What **changes to custom.yaml** are required?

N/A

3. Have you documented any additional setup steps or configurations options?

N/A

4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

cluster should be deployed successfully.
Dashboard should display gm-control card and prometheus should be scraping metrics of gm-control

### CODE REVIEW

**Comment by chrisbsmith** [comment]
@rahug20 please review the failed tests; correct and push another commit

**Comment by chrisbsmith** [comment]
@rahug20 are you keeping both this PR and PR #785 ?  Or can we close this one in favor of #785?

**Comment by rahug20** [comment]
> @rahug20 are you keeping both this PR and PR #785 ? Or can we close this one in favor of #785?

Yes, i am gonna close this one.

**Comment by rahug20** [comment]
Using this PR: https://github.com/greymatter-io/helm-charts/pull/785 now

**Pull request closed without merging**
