### PR TITLE
Modified Spire to auto-generate certs and deploy to other namespaces

### PR DESCRIPTION
**Pull request by zakilur**
**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.

This PR is in response to #886 requesting the ability to deploy Spire to other namespaces. As part of this work, the ability to automatically generate the Spire certificates was also added (the CAs can still be manually provided if desired).
<br/>

2. What **changes to custom.yaml** are required?

The SPIFFE/SPIRE server secrets and webhook and were combined into one file with the auto-generation logic. Some new options were added to the values files as well to control the behavior.
<br/>

3. Have you documented any additional setup steps or configurations options?

The additional configuration options have been documented in the README. 
<br/>

4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

I deployed Grey Matter to my local K3D cluster both while auto-generating the certs and using ones provided in the config. I was able to successfully run Grey Matter and install Fibonacci as a test in both cases.
<br/>

### CODE REVIEW

**Review by chrisbsmith — COMMENTED** [review]
@zakilur i think you'll need to increment the spire chart versions. These changes are enough to warrant a bump to the minor version 

I'd also like @zoemccormick to review as she is out resident Spire expert.

**Review by zoemccormick — DISMISSED** [review]
this looks great! worked perfectly for me - we may want to change the default spire namespace from `test` back to `spire` or something else in the global.yaml file

**Comment by chrisbsmith** [comment]
@zoemccormick do we need to do anything with the default spire domain that's uses throughout the mesh configurations?  the `quickstart.greymatter.io`?

**Comment by zakilur** [comment]
> @zakilur i think you'll need to increment the spire chart versions. These changes are enough to warrant a bump to the minor version
> 
> I'd also like @zoemccormick to review as she is out resident Spire expert.

I just pushed a new commit with the Spire Chart versions updated.

**Comment by zoemccormick** [comment]
nope @chrisbsmith you shouldn't have to. That operates separately from namespace and in the core configs generated by the charts should be configurable with the value of `.Values.global.spire.trust_domain`

**Comment by zakilur** [comment]
> this looks great! worked perfectly for me - we may want to change the default spire namespace from `test` back to `spire` or something else in the global.yaml file

Oops, that was left over from my testing. I changed the default back to `spire` in the most recent commit.

**Comment by zakilur** [comment]
@zoemccormick When you get a chance, could you please re-approve this PR if it looks good to you? The commit I pushed to address the comments invalidated the previous one. Thanks!

**Review by zoemccormick — APPROVED** [review]
lgtm!

**Pull request merged**
