### PR TITLE
Removed duplicate keys from annoations.

### PR DESCRIPTION
**Pull request by jmcudd**
I wasn't sure which to remove, so I just left the last one in each list.

**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.
[Kubernetes Annotations](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/) is an object not a list, duplicate keys are not allowed. Some of the charts had duplicate keys. I only removed the duplicate `checksum/config` keys, as those where the duplicate keys which are currently throwing errors for me in a downstream kustomize repo. 
<br/><br/>

2. What **changes to custom.yaml** are required?
None
<br/><br/>

3. Have you documented any additional setup steps or configurations options?
No
<br/><br/>

4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.
In a downstream kustomize repository I attempted to run HelmChartInflationGenerator on all the charts and got the following error. Upon further investigation of the charts I noticed that the Annotations had duplicate keys which is not allowed in the kubernetes spec.

```kubectl kustomize . --enable-helm
Error: map[string]interface {}(nil): yaml: unmarshal errors:
  line 21: mapping key "checksum/config" already defined at line 20
```
<br/><br/>

### CODE REVIEW

**Comment by dontlaugh** [comment]
@jmcudd what version of helm are you using

**Review by dontlaugh — COMMENTED** [review]
Why are we templating checksums in the first place?

**Comment by jmcudd** [comment]
> @jmcudd what version of helm are you using

`version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"", GoVersion:"go1.16.9"}`



> Why are we templating checksums in the first place?

Very good question.

**Review by dontlaugh — DISMISSED** [review]

**Comment by jmcudd** [comment]
We need to update the README to indicate the new chart versions.

**Review by dontlaugh — APPROVED** [review]

**Comment by dontlaugh** [comment]
merge this if it's green

**Pull request merged**
