### PR TITLE
Global replicas

### PR DESCRIPTION
**Pull request by moosecanswim**
**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.

This allows us to create production ready mesh (meaning multiple replicas).  You can also set the default_replicas.

2. What **changes to custom.yaml** are required?

```
  release:
    production: false
    default_replicas: 3
```
If you set production to false then 3 instances of each service (not control api) will be created

3. Have you documented any additional setup steps or configurations options?

added a note to `### Installing`

4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

I ran make install in a devinabox cluster and this worked.  

set global.release.production to true then run a standard installation.

### CODE REVIEW

**Comment by chrisbsmith** [comment]
> If you set production to false then 3 instances of each service (not control api) will be created

What happens if i set `production` to true?

**Comment by moosecanswim** [comment]
> > If you set production to false then 3 instances of each service (not control api) will be created
> 
> What happens if i set `production` to true?

It will set the replicas of everything except the api to the dumber of replicas specified in default_replicas

**Comment by chrisbsmith** [comment]
> > > If you set production to false then 3 instances of each service (not control api) will be created
> > 
> > 
> > What happens if i set `production` to true?
> 
> It will set the replicas of everything except the api to the dumber of replicas specified in default_replicas

OK, maybe your initial comment is incorrect then.  Here's what I expect:

- when `production` is false (this should be the default): we deploy a single instance of all pods
- when `production` is true, we deploy `default_replicas` (default of 3) number of replicas

Is this accurate?

**Comment by moosecanswim** [comment]
> > > > If you set production to false then 3 instances of each service (not control api) will be created
> > > 
> > > 
> > > What happens if i set `production` to true?
> > 
> > 
> > It will set the replicas of everything except the api to the dumber of replicas specified in default_replicas
> 
> OK, maybe your initial comment is incorrect then. Here's what I expect:
> 
>     * when `production` is false (this should be the default): we deploy a single instance of all pods
> 
>     * when `production` is true, we deploy `default_replicas` (default of 3) number of replicas
> 
> 
> Is this accurate?

Oh whoops.  Yes.  If you set production:true then it will use number specified by default replicas.  If it is false then you will use what is defined in the individual services values.yaml.

If nothing is set anywhere then it will default to 1

**Review by zakilur — APPROVED** [review]
LGTM

**Pull request merged**
