### PR TITLE
securityContextUpdates

### PR DESCRIPTION
**Pull request by chrisbsmith**
The same PR as #911 and #912 but for the release-2.4 branch

### CODE REVIEW

**Review by jimgaspari — APPROVED** [review]
The template changes look good.

**Comment by moosecanswim** [comment]
@chrisbsmith the comments in there say:
```# Security context for openshift, kubernetes and eks is the same.```

So we should probably expand the if block to include those as well.

**Comment by chrisbsmith** [comment]
@zakilur did these changes get included into main when you did the rebase?

**Comment by zakilur** [comment]
> @zakilur did these changes get included into main when you did the rebase?

No, since the PR had not been merged. I only included PRs/commits that had been fully merged into 2.4.

**Comment by zakilur** [comment]
> > @zakilur did these changes get included into main when you did the rebase?
> 
> No, since the PR had not been merged. I only included PRs/commits that had been fully merged into 2.4.

If needed, I can create a new PR against `main` with these changes.

**Comment by zakilur** [comment]
> @zakilur did these changes get included into main when you did the rebase?

Actually, ignore my previous comments. I just went through the code and these changes are present in the `main` branch. They would have been included from the base `release-2.3` branch.

This PR can be closed.

**Comment by chrisbsmith** [comment]
Looking at this again, this was an attempt to merge my changes into release-2.4 after 2.3. I checked and confirmed that the main branch has the same updates. 

Closing.

**Pull request closed without merging**
