### PR TITLE
adding check to make sure user does not enter blank entry

### LINKED ISSUE #628: make credentials should allow for "enter" after the s3 check
As it is, when a user hits `y` or `n` after the prompt `Do you wish to configure S3 credentials for gm-data backing [yn]`

I instinctively hit <enter> after typing `y` and then realized that my aws credentials were blank.

We should also have better error checking, specifically for blank values

### PR DESCRIPTION
**Pull request by rahug20**
**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.

adding code to allow user to not enter empty string when S3 options is chosen

2. What **changes to custom.yaml** are required?

<br/><br/>

3. Have you documented any additional setup steps or configurations options?

<br/><br/>

4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Run `make credentials` and choose option to use S3 and then enter and empty string and then you will seen an error

close #628

### CODE REVIEW

**Review by chrisbsmith — CHANGES_REQUESTED** [review]
@rahug20 When I test this locally, the original code defaults to `* ) echo -e "\nPlease answer yes or no. Defaulting to no S3";;` if `y` or `n` is not provided.  What did you experience that drove this change?

**Review by moosecanswim — APPROVED** [review]
lgtm

**Review by moosecanswim — CHANGES_REQUESTED** [review]
echoing chris;s comment

**Comment by dontlaugh** [comment]
Should this be converted to an issue and closed?

**Comment by chrisbsmith** [comment]
Agree, we'll close for now.

**Pull request closed without merging**
