### PR TITLE
modify the creation of jwt config maps to make it more dynamic

### PR DESCRIPTION
**Pull request by chrisbsmith**
**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.

This change allows us to provide multiple files to the JWT config map generation. This will be useful when deploying a different JWT that needs slightly different configurations.

2. What **changes to custom.yaml** are required?

None, but the config for `fabric/values.yaml` did get updated slightly. The `jwt-users` configMap is now built from `.Values.jwt.files.*`

3. Have you documented any additional setup steps or configurations options?

Additional configuration documentation was addressed in the values.yaml file.

4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Run a `helm template fabric/` and get the following results:

```
---
# Source: fabric/charts/jwt/templates/jwt-users.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: jwt-users
  namespace: default
data:
  users.json: |
    {
      "users": [
      {
        "label": "CN=localuser,OU=Engineering,O=Decipher Technology Studios,=Alexandria,=Virginia,C=US",
        "values": {
          "email": [
            "localuser@greymatter.io"
          ],
          "org": [
            "www.greymatter.io"
          ],
          "privilege": [
            "root"
          ]
        }
      },
      {
        "label": "CN=gm-control,OU=Engineering,O=Decipher Technology Studios,=Alexandria,=Virginia,C=US",
        "values": {
          "email": [
              "gm-control@greymatter.io"
          ],
          "org": [
              "www.greymatter.io"
          ],
          "privilege": [
              "root"
          ]
        }
      },
      {
        "label": "CN=gm-catalog,OU=Engineering,O=Decipher Technology Studios,=Alexandria,=Virginia,C=US",
        "values": {
          "email": [
              "engineering@greymatter.io"
          ],
          "org": [
              "www.greymatter.io"
          ],
          "privilege": [
              "root"
          ]
        }
      },
      {
        "label": "CN=greymatter,OU=Engineering,O=Decipher Technology Studios,L=Alexandria,ST=Virginia,C=US",
        "values": {
          "email": [
              "engineering@greymatter.io"
          ],
          "org": [
              "www.greymatter.io"
          ],
          "privilege": [
              "root"
          ]
        }
      },
      {
        "label": "CN=greymatter.user",
        "values": {
          "email": [
              "engineering@greymatter.io"
          ],
          "org": [
              "www.greymatter.io"
          ],
          "privilege": [
              "root"
          ]
        }
      },
      {
        "label": "O=SPIRE,C=US",
        "values": {
          "email": [
              "engineering@greymatter.io"
          ],
          "org": [
              "www.greymatter.io"
          ],
          "privilege": [
              "root"
          ]
        }
      }]
    }
---
```

Now create a new file with more config files:
```
jwt:
  jwt:
    files: 
      test.json: |
        {
          "content": "test data"
        }
```

Run the helm template again, but with the new file
```
helm template fabric/ -f test.yaml
```

```
---
# Source: fabric/charts/jwt/templates/jwt-users.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: jwt-users
  namespace: default
data:
  test.json: |
    {
      "content": "test data"
    }

  users.json: |
    {
      "users": [
      {
        "label": "CN=localuser,OU=Engineering,O=Decipher Technology Studios,=Alexandria,=Virginia,C=US",
        "values": {
          "email": [
            "localuser@greymatter.io"
          ],
          "org": [
            "www.greymatter.io"
          ],
          "privilege": [
            "root"
          ]
        }
      },
      {
        "label": "CN=gm-control,OU=Engineering,O=Decipher Technology Studios,=Alexandria,=Virginia,C=US",
        "values": {
          "email": [
              "gm-control@greymatter.io"
          ],
          "org": [
              "www.greymatter.io"
          ],
          "privilege": [
              "root"
          ]
        }
      },
      {
        "label": "CN=gm-catalog,OU=Engineering,O=Decipher Technology Studios,=Alexandria,=Virginia,C=US",
        "values": {
          "email": [
              "engineering@greymatter.io"
          ],
          "org": [
              "www.greymatter.io"
          ],
          "privilege": [
              "root"
          ]
        }
      },
      {
        "label": "CN=greymatter,OU=Engineering,O=Decipher Technology Studios,L=Alexandria,ST=Virginia,C=US",
        "values": {
          "email": [
              "engineering@greymatter.io"
          ],
          "org": [
              "www.greymatter.io"
          ],
          "privilege": [
              "root"
          ]
        }
      },
      {
        "label": "CN=greymatter.user",
        "values": {
          "email": [
              "engineering@greymatter.io"
          ],
          "org": [
              "www.greymatter.io"
          ],
          "privilege": [
              "root"
          ]
        }
      },
      {
        "label": "O=SPIRE,C=US",
        "values": {
          "email": [
              "engineering@greymatter.io"
          ],
          "org": [
              "www.greymatter.io"
          ],
          "privilege": [
              "root"
          ]
        }
      }]
    }
---
```

Verify that the test file is created.

You can also apply these to a k3d environment.

```
helm install fabric . --set=global.waiter.service_account.create=false -f ../global.yaml -f ../test.yaml
```

```
➜  ~ kc get cm jwt-users -o yaml
apiVersion: v1
data:
  test.json: |
    {
      "content": "test data"
    }
  users.json: |
    {
      "users": [
      {
        "label": "CN=localuser,OU=Engineering,O=Decipher Technology Studios,=Alexandria,=Virginia,C=US",
        "values": {
          "email": [
            "localuser@greymatter.io"
          ],
          "org": [
            "www.greymatter.io"
          ],
          "privilege": [
            "root"
          ]
        }
      },
      {
        "label": "CN=gm-control,OU=Engineering,O=Decipher Technology Studios,=Alexandria,=Virginia,C=US",
        "values": {
          "email": [
              "gm-control@greymatter.io"
          ],
          "org": [
              "www.greymatter.io"
          ],
          "privilege": [
              "root"
          ]
        }
      },
      {
        "label": "CN=gm-catalog,OU=Engineering,O=Decipher Technology Studios,=Alexandria,=Virginia,C=US",
        "values": {
          "email": [
              "engineering@greymatter.io"
          ],
          "org": [
              "www.greymatter.io"
          ],
          "privilege": [
              "root"
          ]
        }
      },
      {
        "label": "CN=greymatter,OU=Engineering,O=Decipher Technology Studios,L=Alexandria,ST=Virginia,C=US",
        "values": {
          "email": [
              "engineering@greymatter.io"
          ],
          "org": [
              "www.greymatter.io"
          ],
          "privilege": [
              "root"
          ]
        }
      },
      {
        "label": "CN=greymatter.user",
        "values": {
          "email": [
              "engineering@greymatter.io"
          ],
          "org": [
              "www.greymatter.io"
          ],
          "privilege": [
              "root"
          ]
        }
      },
      {
        "label": "O=SPIRE,C=US",
        "values": {
          "email": [
              "engineering@greymatter.io"
          ],
          "org": [
              "www.greymatter.io"
          ],
          "privilege": [
              "root"
          ]
        }
      }]
    }
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: fabric
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-07-26T16:31:39Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: jwt-users
  namespace: default
  resourceVersion: "1772"
  uid: 88b84293-a95d-46f1-8c09-7abed9ae7305
```

### CODE REVIEW

**Review by jimgaspari — APPROVED** [review]
These changes look good.

**Comment by jimgaspari** [comment]
Do these changes remove the need for the jwt-gov fabric helm charts?

**Comment by chrisbsmith** [comment]
> @chrisbsmith Do these changes remove the need for the jwt-gov fabric helm charts?

@jimgaspari Yes, it should but I haven't actually tested a full gov deployment. My goal was to remove the jwt-gov chart with another commit.

**Review by moosecanswim — APPROVED** [review]
lgtm

**Pull request merged**
