### PR TITLE
fresh code to add sidecar to control

### PR DESCRIPTION
**Pull request by rahug20**
**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.

Another MR in which sidecar is being added to control without the use of static sidecar configs.

2. What **changes to custom.yaml** are required?

N/A

3. Have you documented any additional setup steps or configurations options?

N/A

4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Comment out `make data` from global Makefile

and 

Run `make install`

Cluster should be successfully deployed with control having a sidecar in front of it.

### CODE REVIEW

**Comment by chrisbsmith** [comment]
@rahug20 - check the status checks.  Looks like you need to update some chart versions. May need to time with this @zakilur as he may merge a PR first.

**Comment by rahug20** [comment]
> @rahug20 - check the status checks. Looks like you need to update some chart versions. May need to time with this @zakilur as he may merge a PR first.

Yes, i will update the chart versions once the bug that we had found is addressed and the PR is working.

**Comment by kaitmore** [comment]
@rahug20 @chrisbsmith 

Heads up - I pushed up a couple commits here that gets this almost working. If you spin this branch up all sidecars receive their configs, but services appear down in the dashboard. This is because catalog has no ability to connect to control with TLS. Here is the relevant issue: https://github.com/greymatter-io/gm-catalog/issues/383

@bcmendoza is working on this now - we'll have to wait for catalog@1.2.0 to be cut before merging this branch

**Comment by chrisbsmith** [comment]
@kaitmore, we're not going to prioritize this for 1.3 release.  This is a rather large change to business and I want to make sure we have a solid testing of it before we push it through.

**Comment by kaitmore** [comment]
@chrisbsmith Understood, thanks. 👍

**Comment by alecholmez** [comment]
Just updated this PR based off the 2.3 version changes

**Review by chrisbsmith — CHANGES_REQUESTED** [review]
I'm going to put a "hold" on this PR until after the 1.3 release, unless there is a legit reason why we need to include it in 1.3.  At this point, we're a few weeks away from the release and we're already underway with testing. 

I would like to get sufficient test time on this change, since it's a rather large change, and push it out with the 1.4 release.

@alecholmez @rahug20 @zoemccormick @justincely @tilleryd, if you disagree, let's have a discussion. Otherwise, I'm leaving my "request changes" review on the PR.

**Comment by alecholmez** [comment]
Works for me, I'm just using this branch for my incremental xDS testing so I'm in no rush

**Comment by justincely** [comment]
@chrisbsmith correct, we don't _need_ to include it for 1.3.   1.3 brings in enough support so that we CAN, and there are  things it enables in the future.  So lets not let this languish, but it's fine to push as  an update after the release.

**Comment by chrisbsmith** [comment]
@justincely as soon as we cut a `release-2.3` branch, we should create a `release-2.4` branch and push this PR there.

**Comment by alecholmez** [comment]
Just leaving this here for notes later:

Right now the sidecar in front of control is causing issues with connecting proxies. It seems they connect initially but after some amount of random time, their connections get dropped and then they fail to reconnect with the xDS server. Errors regarding incorrect nonces for new streams begin to popup through control logs as well due to the dropped connection.

**Comment by chrisbsmith** [comment]
Way to test @alecholmez!

**Comment by justincely** [comment]
@rahug20 @chrisbsmith i think this is good to go after @alecholmez's additions?  can we get a re-review/update on this?  (or can have product folks take it if you're swamped)

**Comment by chrisbsmith** [comment]
If you have a feee product resource that would help. I'd like to focus this on the release-2.4 branch though, so we may need to close this pr and open a new one against the other branch.

**Comment by tilleryd** [comment]
@jack-bischoff Passing the torch onto you to test this.

**Comment by tilleryd** [comment]
Replaced by https://github.com/greymatter-io/helm-charts/pull/876

**Pull request closed without merging**
